### ISSUE TITLE
[Experimental] Windows support in Istio Data Plane

### ISSUE THREAD

**Issue by sunjayBhatia** [istio/enhancements#10]
# Feature:

**Feature name:**

Support Windows in data plane (sidecar injection and traffic capture)

**Primary lead(s):**

@sunjayBhatia

**Short description:**

This feature intends to support Windows applications deployed in Kubernetes in an Istio service mesh. Windows developers/operators should have (pragmatic) parity in features they can use to observe, manage, etc. their service mesh including Windows applications.

# Requirements:

- [ ] [User stories](insert_your_link_here) reviewed in a work group meeting.

[//]: # (User stories are a way to communicate user value. User stories follow the style)
[//]: # (as a [type of user], I want [an action] so that [a benefit/a value]. Istio currently has no user)
[//]: # (story template. Maybe you can make one?)

[//]: # (User stories must be presented in a work group meeting. They need no approval and are later integrated)
[//]: # (into the RFCs, which do need approval for alpha. You may find value to negotiate within the work group where the)
[//]: # (user stories are presented to help clarify the user stories.)

- [x] [Istio RFC: Windows Support in Istio Data Plane](https://docs.google.com/document/d/1nlEeo_PDoZtb9MHB1L9JpnbdU8efpcGJwQDwlWz7LXk/edit?usp=sharing) (not yet in Istio team drive, may be moved - did you wish this to be moved to the team drive?)

- [ ] [Documentation](insert_your_link_here) for enabling and using the feature.

[//]: # (The documentation instructions may exist on the developer wiki or the team drive. They may include instructions)
[//]: # (for building running a `istioctl experimental command`, or using the preview profile,)
[//]: # (or any other relevant information.)

- [ ] [Feedback plan](insert_your_link_here).

[//]: # (This may include user feedback meetings, discuss.istio.io conversations, GitHub issues, or mailing lists.)

- [ ] Disabled by default.

- [ ] No impact on performance when the feature is disabled.

### Links
- https://github.com/istio/istio/issues/27893

**Comment by sunjayBhatia** [comment]
An update from VMware: currently this work has been deprioritized for us, however happy to pass on ownership of this issue/RFC etc. to any interested parties

cc @daschott if you have anyone at Microsoft who is interested

**Comment by Type1J** [comment]
That is unfortunate.

**Comment by brian-avery** [comment]
Migrated to https://github.com/brian-avery/enhancements/blob/migrateFeaturesToFiles/features/windows_data_plane_support.md as part of #26

**Comment by sunjayBhatia** [comment]
Updated google doc link: https://docs.google.com/document/d/19yyh5FFRX1y_jEqrHNKAoDU_ycsZrj_Wk1mnTV075gs/edit?usp=sharing
