### ISSUE TITLE
[Alpha] External Istiod

### ISSUE THREAD

**Issue by linsun** [istio/enhancements#11]
# Alpha Feature Requirements

This page lists the requirements for promoting a feature to alpha. Please check off and document the steps as they are completed.

**Feature Name:**  
External Istiod (formerly called central istiod)

**RFC:**
https://docs.google.com/document/d/1r58al52otp1uvB7YFHh8ifA_78hYeyd0hNLq4qPDSUM/edit

**Design doc:**
https://docs.google.com/document/d/1EymnzMqa7hdmKn8sEoaf1elajyp4gXEDSUavxzXB3jw/edit#

**Relevant Documentation:**
[https://preliminary.istio.io/latest/docs/setup/additional-setup/external-controlplane/](https://preliminary.istio.io/latest/docs/setup/additional-setup/external-controlplane/)
--- 

### Requirements: 

**Design**

- [x] RFC has been approved describing the intention of the feature as well as the user stories behind the feature. 

**Config**

- [x] Explicit user action is required to enable this feature (e.g. a config field, config resource, or installation action). 

> Link to instructions for enabling

**Docs**

- [x] Reference docs are published to preliminary.istio.io or the Istio wiki (https://preliminary.istio.io/latest/docs/setup/additional-setup/external-controlplane/)
- [x] Basic feature docs are published on preliminary.istio.io describing what the feature does, how to use it, and any caveats. 
- [] Release notes entries added as appropriate - WIP
- [] Upgrade notes entries added as appropriate - doesn't apply

**Tests**

- [x] Automated integration tests cover core use cases with the feature enabled. 
- [x] When disabled, the feature does not affect system stability or performance. 

**API**

- [x] Initial API review.  (No API added in 1.8)

**Approvals**

- [x] The appropriate work group(s) have reviewed and approved promotion of the feature.
- [ ] The TOC has reviewed and approved promotion of the feature as part of the
	roadmap for a release.

**Comment by linsun** [comment]
@sdake @ostromart @costinm could I get approval on this?

The docs section is lacking, but being actively worked on:

https://github.com/istio/istio.io/pull/8403
Preview:  https://deploy-preview-8403--preliminary-istio.netlify.app/latest/docs/setup/additional-setup/external-istiod/

Release notes/upgrade notes entry was added as experimental in 1.7 and will be added as an alpha feature as soon as the promotion to alpha is approved.

**Comment by ostromart** [comment]
LGTM

**Comment by sdake** [comment]
LGTM.

**Comment by linsun** [comment]
Thanks @ostromart @sdake.  Doc is also published, I've updated the checklist earlier with WG approval.

**Comment by linsun** [comment]
@istio/technical-oversight-committee seeking TOC approval, PTAL

**Comment by nrjpoddar** [comment]
@linsun can you add the prelim doc links so I can take a look?

**Comment by linsun** [comment]
@nrjpoddar here you go - https://preliminary.istio.io/latest/docs/setup/additional-setup/external-controlplane/

**Comment by nrjpoddar** [comment]
This looks good, approved from my end!

**Comment by sdake** [comment]
@linsun would you be kind enough to submit a feature status page update as @bianpengyuan has done here for this feature promotion?

https://github.com/istio/istio.io/pull/8453#pullrequestreview-525841182

Cheers,
-steve

**Comment by linsun** [comment]
@smawson @dcberg @louiscryan @duderino another friendly ping - seeking TOC approval, PTAL

**Comment by smawson** [comment]
Approved from me!  A couple minor nits:
- RFC needs to be marked as approved and missing a few official signoffs.
- istio.io docs should indicate this is in alpha

Otherwise looks good, this is a great feature.

**Comment by dcberg** [comment]
+1

**Comment by louiscryan** [comment]
+1

**Comment by linsun** [comment]
Thank you all, much appreciated, I'll mark this as approved!!
