### ISSUE TITLE
[Alpha] Helm v3 support

### ISSUE THREAD

**Issue by nrjpoddar** [istio/enhancements#12]
# Alpha Feature Requirements

This page lists the requirements for promoting a feature to alpha. Please check off and document the steps as they are completed.

**Feature Name:** 
Helm support

**RFC:**
[Approved by Environment WG - Helm v3 support](https://docs.google.com/document/d/1upInT_Qe3-CU2ig_XnUNjP2wLyBr6ImpJfMXvz-BYec/edit#heading=h.h4dnnbkwzgzw)

**Design doc:**
NA

**Relevant Documentation:**
1. https://preliminary.istio.io/latest/docs/setup/install/helm/
1. https://preliminary.istio.io/latest/faq/setup/
--- 

### Requirements: 

**Design**

- [x] RFC has been approved describing the intention of the feature as well as the user stories behind the feature. 

**Config**

- [x] Explicit user action is required to enable this feature (e.g. a config field, config resource, or installation action). 

> https://preliminary.istio.io/latest/docs/setup/install/helm/

**Docs**

- [x] Reference docs are published to preliminary.istio.io or the Istio wiki.
- [x] Basic feature docs are published on preliminary.istio.io describing what the feature does, how to use it, and any caveats. 
- [x] Release notes entries added as appropriate
- [ ] ~~Upgrade notes entries added as appropriate~~ (NA) as only upgrades from 1.8.x and above are supported.

**Tests**

- [x] Automated integration tests cover core use cases with the feature enabled.
> https://github.com/istio/istio/tree/1ec9f765e3b938b519e393c8a04675cfc6d0470b/tests/integration/helm 
- [x] When disabled, the feature does not affect system stability or performance. 

**API**

- [ ] ~~Initial API review.~~
   Helm install/upgrade commands are well known APIs. Configuring options via Helm values is considered experimental and will be matured in 1.9 and above.

**Approvals**

- [x] The appropriate work group(s) have reviewed and approved promotion of the feature.
- [x] The TOC has reviewed and approved promotion of the feature as part of the
	roadmap for a release.

**Comment by bianpengyuan** [comment]
Looks like not all check boxes have been ticked. Does those items not apply here or are they still WIP?

**Comment by nrjpoddar** [comment]
You're currently working on release/upgrade notes :)

I will update the other ones as I ping WG/TOC leads.

**Comment by nrjpoddar** [comment]
@ostromart @costinm @sdake PTAL so I can tick the WG approval checkbox.

**Comment by nrjpoddar** [comment]
Note that I had to add [this doc change](https://github.com/istio/istio.io/pull/8475) to account for hub/tag in released manifests being incorrect. We should take that into account as we explore whether Helm support should be deemed alpha or experimental.

**Comment by ostromart** [comment]
Approved for alpha by Environments WG.

**Comment by nrjpoddar** [comment]
@linsun @smawson can you approve this? I will add release notes once "alpha" is approved.

**Comment by ostromart** [comment]
regarding the missing docs: https://github.com/istio/istio.io/issues/7824

**Comment by smawson** [comment]
This is missing a few things:
1) The RFC is not actually approved (no approvers are listed, not enough WGs involved. Can't just ask for approvals here we want to track this on the doc)
2) The API has not been reviewed (here the API is whatever the helm API is that we're exposing to users).
3) AFAIK this hasn't been formally discussed in TOC. Let's put on Friday agenda to make sure we're OK making helm v3 supported in 1.8 (I am OK with it but want to follow the process).

**Comment by nrjpoddar** [comment]
Makes sense. A lot of this formal process came after the Helm support began which is leading to mismatch. Either way let’s discuss it during TOC. I’m totally fine not adding Helm support or making it experimental or removing docs.

**Comment by leecalcote** [comment]
Have users given significant pushback on the removal of Helm support or has that feedback been negligible?

**Comment by linsun** [comment]
@nrjpoddar the Helm install/upgrade doc looks good to me, I learned Helm also support revision natively.:)

I think the way we are positioning Helm vs istioctl makes sense.  Given we have lots of users asking for Helm v3 and you are willing to step up to support it, I'm good with alpha for 1.8, assuming you secure the RFC approvals and no strong objections from others in Friday's TOC mtg.

**Comment by linsun** [comment]
One q - is it only intended to install from istio release binary?  Any thoughts on installing it from a helm remote repo?

**Comment by smawson** [comment]
Just to be clear I think we should include this in 1.8 since customers want it, just wanted us to discuss it and not assume it.

**Comment by smawson** [comment]
Looking over the docs, I don't see any documentation of the values supported. How do users know what values are supported and what they mean?

**Comment by nrjpoddar** [comment]
> Looking over the docs, I don't see any documentation of the values supported. How do users know what values are supported and what they mean?

That's why I added this statement: "Another thing to consider is the overrides values for Helm (also for Operator API) is not documented on your site and can only be discovered via the released manifest charts."

I don't know what to do here as Operator also says to use values but we don't document it anywhere.

**Comment by nrjpoddar** [comment]
Notes from Environments WG discussion on 11/11/2020:

1. WG approved the [RFC](https://docs.google.com/document/d/1upInT_Qe3-CU2ig_XnUNjP2wLyBr6ImpJfMXvz-BYec/edit#heading=h.h4dnnbkwzgzw)
1. Doc changes required before marking the support Alpha:
  1. Mention that customizing of charts via values is experimental is likely to change in future releases
  1. Users can find the options by looking at individual chart values.yaml files
  1. Users should use `meshConfig` options where supported
  1. Add a note about "canary" upgrades as the recommended approach over "in-place"
1. @costinm to fix templates in 1.8 and master so that `--hub` option is not needed. This is not a blocker for making it "alpha"
1. Lack of configuration API or stability is also not a blocker for "alpha" from WG point of view.

**Comment by nrjpoddar** [comment]
> One q - is it only intended to install from istio release binary? Any thoughts on installing it from a helm remote repo?

Currently, discovering of charts is only via the Istio release packages as we don't publish the charts in a centralized 3rd party repo.

**Comment by nrjpoddar** [comment]
> Have users given significant pushback on the removal of Helm support or has that feedback been negligible?

Yes, we have had quite a few users who wanted Helm v3 support and who have been stuck at older versions due to removal of Helm support.

**Comment by smawson** [comment]
Can I make it a requirement that from the docs we describe how to see what options are supported? A link to the repo containing the charts would be fine for alpha.
