### ISSUE TITLE
Review Issues related to Telemetry API

### ISSUE THREAD

**Issue by imnmo** [istio/enhancements#157]
Related to https://github.com/istio/enhancements/issues/155 

**Description:** 
Conduct a comprehensive review of existing GitHub issues in the [istio](https://github.com/istio/istio) and [api](https://github.com/istio/api) repositories to identify any issues related to custom tags for trace spans and non-default/multiple telemetry providers in the mesh.

**Comment by whitneygriffith** [comment]
Part of #155

**Comment by imnmo** [comment]
So far the findings for custom tags:

Only one issue is relevant to this feature and open : 
[Adding custom Tags Duplicates Metrics](https://github.com/istio/istio/issues/39772 ) Open - its resolved but not closed the plan to review them after the Telemetry API promoted to beta
