### ISSUE TITLE
Istio Configuration Status - Beta

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/enhancements#17]
# Beta Feature Requirements

This page lists the requirements for promoting a feature to beta. Promotion to beta must meet all requirements for promotion to alpha. Please check off and document the steps as they are completed.

**Feature Name:** 
Configuration Status

**Design Doc:**
https://docs.google.com/document/d/13z0K3mVof0KlE9wZenE6RNmr01YJdGelxHcGKt36dNA
https://docs.google.com/document/d/1J-yRkDlwQ9NBN4gjYXY-tvqSNE0N01sMKevuLBqjltA

**Alpha Checklist:**

**Relevant Documentation:**

--- 

### Requirements: 

**Design**

- [x] Design doc describing the intention of the feature, how it will be
	implemented, and any thoughts on how to test the feature has been approved by
	relevant work group leads
- [x] Feature coverage and test plans written and approved.

**Docs** 

- [x] Documentation on istio.io includes performance expectations; may have caveats. 
- [x] Documentation on istio.io includes samples/tutorials. 
- [x] Documentation on istio.io includes appropriate glossary entries. 
- [ ] All new documentation containing user actions includes istio.io tests.
- [ ] Release notes have been added. 
- [ ] Upgrade notes have been added. 

**Tests**

- [x] Integration tests cover feature edge cases
- [x] End-to-end tests cover samples/tutorials
- [x] Fixed issues have tests to prevent regressions
- [ ] Stability/stress test suite includes coverage for the feature.

**Performance**

- [x] Feature coverage and test plans written and approved 
- [x] Tests exist with the feature enabled that can be integrated with our automated performance testing.

**API**

- [x] TOC has reviewed the API and determined it to be complete. 

**Tooling**

- [x] Any necessary tooling to use/debug the feature has been implemented and is complete. 

**Bugs**

- [x] Feature has no known major issues.

**Approvals**

- [x] The appropriate work group(s) have reviewed and approved promotion of the feature.
- [x] The supportability review panel has reviewed promotion of the feature.  
- [ ] The TOC has reviewed and approved promotion of the feature as part of the
	road map for a release.

**Comment by howardjohn** [comment]
> TOC has reviewed the API and determined it to be complete.

A bit fuzzy on the details, but I recall some contention around what is actually exposed in the status ("8/8 proxies" vs "distributed"), which I don't think was every resolved.

> Feature has no known major issues.

Can we track the known issues? I know you have some fixes outstanding, so lets make sure we are tracking these rather than assuming they are done - we are unable to enable this in CI currently since it crashes often. I just want to make sure we don't prematurely forget about these

**Comment by howardjohn** [comment]
One thing we should consider is if https://github.com/istio/istio/issues/23943 is a blocker. It feels odd to promote something to beta when the core implementation is scheduled to be completely overhauled. I am a bit conflicted, as I don't really want to keep moving the stick just out of reach, but it would be really nice for galley/ to be gone.

**Comment by esnible** [comment]
We are tracking the config status issues in https://github.com/istio/istio/issues/30179

**Comment by brian-avery** [comment]
Migrated to https://github.com/brian-avery/enhancements/blob/migrateFeaturesToFiles/features/configuration_status.md as part of #26
