### ISSUE TITLE
[beta] Virtual Machines

### ISSUE THREAD

**Issue by howardjohn** [istio/enhancements#18]
# Beta Feature Requirements

This page lists the requirements for promoting a feature to beta. Promotion to beta must meet all requirements for promotion to alpha. Please check off and document the steps as they are completed.

**Feature Name:** Virtual Machines

**Design Doc:**

- https://docs.google.com/document/d/1aMdRacznhGUsBWTx-KNzYEcEPKDgVtVQBLcRCBAMTb8
- https://docs.google.com/document/d/1VDV4-prbMbzW06hslfp12sn7V6oUvnIAst6mT6FtSWc
- https://docs.google.com/document/d/10TyPy-6bOs0_7JljGpc2RneDdsaR9GktjwwaaVbz6fs
- https://docs.google.com/document/d/1G4s_PrmvkwCKoH_kXVeSUAszsaj3ZfpIlraSdeTSPKU
- https://docs.google.com/document/d/1BuwOX6D30Yy6lTvj4RHwLzcUoaAu61pAdtKnLx312ec
- https://docs.google.com/document/d/1-612Sgz_skeoX44dw3MU6Z8ONgq1f29wLUI9zggyLec
- https://docs.google.com/document/d/1QReA8XjWrWTnErQYPZUdPA5d2O6fc3VkLWr47hY0Nbg
- https://docs.google.com/document/d/1-RVOpCGbcDdr-yM4UrT0WgfHZglgQZlPL1d1aZbqEbk

**Alpha Checklist:**

**Relevant Documentation:**

- https://preliminary.istio.io/latest/docs/setup/install/virtual-machine/
- https://preliminary.istio.io/latest/docs/examples/virtual-machines/

### Requirements: 

**Design**

- [x] Design doc describing the intention of the feature, how it will be
	implemented, and any thoughts on how to test the feature has been approved by
	relevant work group leads.
**YES**: see links above. The design docs cover every working group; this feature has been collaborated on by all groups.
- [x] Feature coverage and test plans written and approved.

**Docs** 

- [x] Documentation on istio.io includes performance expectations; may have caveats. **YES**: VMs do not have a different performance profile from Kubernetes pods.
- [x] Documentation on istio.io includes samples/tutorials.  **YES**: See docs above
- [x] Documentation on istio.io includes appropriate glossary entries.  **YES**: This feature does not introduce new vocabulary.
- [x] All new documentation containing user actions includes istio.io tests. **YES**: the docs have tests
- [x] Release notes have been added.  **YES**: Individual features have release notes
- [x] Upgrade notes have been added.  **YES**: No upgrade notes have been needed, as these are new features.

**Tests**

- [x] Integration tests cover feature edge cases. **YES**: we have VM's as part of networking, security, and telemetry tests
- [x] End-to-end tests cover samples/tutorials. **YES**:  docs all have tests, and we have extensive
- [x] Fixed issues have tests to prevent regressions. **YES**: We have included regression tests for various WorkloadEntry bugs and for certificate rotation bugs
- [x] Stability/stress test suite includes coverage for the feature.  **YES**: we have added vm

**Performance**

- [x] Feature coverage and test plans written and approved 
- [x] Tests exist with the feature enabled that can be integrated with our automated performance testing.  **YES**: https://github.com/istio/tools/pull/1432

**API**

- [x] TOC has reviewed the API and determined it to be complete.  **YES**: all APIs (workload entry, workload group) were approved during their introduction.

**Tooling**

- [x] Any necessary tooling to use/debug the feature has been implemented and is complete.  **YES**: istioctl has commands to bootstrap VMs, and has support for common commands like `proxy-config` and `proxy-status`.

**Bugs**

- [x] Feature has no known major issues.

**Approvals**

- [x] The appropriate work group(s) have reviewed and approved promotion of the feature.
  - [x] Environments
  - [x] Networking
  - [x] Security
  - [x] Telemetry
- [x] The supportability review panel has reviewed promotion of the feature.
   - [Meeting results](https://docs.google.com/document/d/1mSB5r2RwegClg5TY3m5yr5Cgf6mvtvqRFmrfmX1DU2c/edit#). Some documentation updates are blocking.
- [x] The TOC has reviewed and approved promotion of the feature as part of the
	road map for a release.

**Comment by sdake** [comment]
@howardjohn - awesome work John. Approving the plan for Environments.

**Comment by liminw** [comment]
Approving for security. Thanks @howardjohn.

**Comment by howardjohn** [comment]
Somehow TOC doc had deleted comments, so copying discussion here:

* docs have been identified that needs to be created.  Approving to beta now would be conditional on docs being updated
* stability tests don't currently exercise VMs.  work is scheduled to add this.   Approving to beta now would trust us that we will add this later.   can do a laborious one-time manual test until we add VM tests to the stability test suite. 
   * This is a blocker for beta but see decision below about promoting to beta in a patch release
* doc automated testing doesn't exist (and is hard to run against real VMs - and slow even if we could get it to work).  Approving to beta now would give a long-lasting exception to this requirement.  linsun - strong preference.  howardjohn - might be lower cost than stability test.  sven- this is a blocker.
* if there are no feature additions (just bug fixes), can we promote to beta in a 1.9 patch release once blockers have been met?   
   * TOC approves assuming that this scenario is identified in the 1.9 release notes.  Also in 1.10 should announce the feature as beta in its release notes.

**Comment by howardjohn** [comment]
TOC blockers are complete, just waiting for async signoff after review

**Comment by duderino** [comment]
I approve for beta for 1.9.   @smawson @nrjpoddar @linsun @louiscryan works?

**Comment by nrjpoddar** [comment]
Approved!

**Comment by louiscryan** [comment]
Approved

**Comment by linsun** [comment]
Nice work @howardjohn, approved!  Enjoyed reading this too - https://preliminary.istio.io/latest/docs/ops/deployment/vm-architecture/

**Comment by smawson** [comment]
Awesome work John and team, approved! And echoing Lin, thanks for putting in the effort on docs!

**Comment by howardjohn** [comment]
Thanks everyone involved! This was a big effort by every working group and pretty much everyone involved in the project. Super happy to see this through!

I think the idea is these issues are closed once complete, so I'll close this.
