### ISSUE TITLE
[Alpha] service-apis

### ISSUE THREAD

**Issue by howardjohn** [istio/enhancements#19]
# Alpha Feature Requirements

This page lists the requirements for promoting a feature to alpha. Please check off and document the steps as they are completed.

**Feature Name:**  service-apis support

**RFC:** https://docs.google.com/document/d/1_TqSdh5z_ANk441U85oNMQWWLZp3McGWmyc-fDGI1t8/

**Design doc:** https://docs.google.com/document/d/1_TqSdh5z_ANk441U85oNMQWWLZp3McGWmyc-fDGI1t8/

**Relevant Documentation:** https://preliminary.istio.io/latest/docs/tasks/traffic-management/ingress/service-apis/

--- 

### Requirements: 

**Design**

- [x] RFC has been approved describing the intention of the feature as well as the user stories behind the feature. 

**Config**

- [x] Explicit user action is required to enable this feature (e.g. a config field, config resource, or installation action). 
       YES: User needs to create the service-apis CRDs and resources explicitly: https://preliminary.istio.io/latest/docs/tasks/traffic-management/ingress/service-apis/

**Docs**

- [x] Reference docs are published to preliminary.istio.io or the Istio wiki. https://preliminary.istio.io/latest/docs/tasks/traffic-management/ingress/service-apis/
- [x] Basic feature docs are published on preliminary.istio.io describing what the feature does, how to use it, and any caveats.  https://preliminary.istio.io/latest/docs/tasks/traffic-management/ingress/service-apis/
- [x] Release notes entries added as appropriate
- [x] Upgrade notes entries added as appropriate

**Tests**

- [x] Automated integration tests cover core use cases with the feature enabled. [YES](https://github.com/istio/istio/blob/d7602c2f2d4da2560e8e555ad18edc9174913a58/tests/integration/pilot/ingress_test.go#L34)
- [x] When disabled, the feature does not affect system stability or performance. YES: No impact on system when CRDs are not present

**API**

- [X] Initial API review. N/A: API is not owned by Istio. But its been extensively reviewed in the Kubernetes community, with heavy inputs from Istio.

**Approvals**

- [x] The appropriate work group(s) have reviewed and approved promotion of the feature.
- [x] The TOC has reviewed and approved promotion of the feature as part of the roadmap for a release.

**Comment by duderino** [comment]
approve for alpha for 1.9

@louiscryan @smawson @linsun @nrjpoddar works?

**Comment by nrjpoddar** [comment]
Approved.

**Comment by linsun** [comment]
Approved, nice doc and test for the doc @howardjohn !

**Comment by louiscryan** [comment]
Approved

**Comment by smawson** [comment]
Approved!

**Comment by howardjohn** [comment]
Thanks everyone!

**Comment by brian-avery** [comment]
Migrated to https://github.com/brian-avery/enhancements/blob/migrateFeaturesToFiles/features/service_apis.md as part of #26
