### ISSUE TITLE
[Alpha] Better External Authorization

### ISSUE THREAD

**Issue by yangminzhu** [istio/enhancements#23]
# Alpha Feature Requirements

This page lists the requirements for promoting a feature to alpha. Please check off and document the steps as they are completed.

**Feature Name:**  Better External Authorization

**RFC:** See the design doc that includes all information

**Design doc:** https://docs.google.com/document/d/1V4mCQCw7mlGp0zSQQXYoBdbKMDnkPOjeyUb85U07iSI/edit

**Relevant Documentation:** https://istio.io/latest/blog/2021/better-external-authz/

--- 

### Requirements: 

**Design**

- [x] RFC has been approved describing the intention of the feature as well as the user stories behind the feature. 

(there is no separate RFC, the design doc is approved)

**Config**

- [x] Explicit user action is required to enable this feature (e.g. a config field, config resource, or installation action). 

(the user needs to configure extension provider and authz policy to enable the feature, see task in https://istio.io/latest/docs/tasks/security/authorization/authz-custom/)

**Docs**

- [x] Reference docs are published to preliminary.istio.io or the Istio wiki. (https://istio.io/latest/docs/tasks/security/authorization/authz-custom/)
- [x] Basic feature docs are published on preliminary.istio.io describing what the feature does, how to use it, and any caveats.  ( (https://istio.io/latest/docs/tasks/security/authorization/authz-custom/)
- [ ] Release notes entries added as appropriate (https://istio.io/latest/news/releases/1.9.x/announcing-1.9/change-notes/#security added the feature as experimental. Will need another PR for promoting to alpha in the release notes)
- [ ] Upgrade notes entries added as appropriate (WIP)

**Tests**

- [x] Automated integration tests cover core use cases with the feature enabled. (https://github.com/istio/istio/blob/6d5406628e2fa9bd2fa31e9b4bc5d05186e01bd6/tests/integration/security/authorization_test.go#L1256 and https://github.com/istio/istio.io/pull/9422)
- [x] When disabled, the feature does not affect system stability or performance. (No filter generated when the feature is disabled)

**API**

- [ ] Initial API review. (https://github.com/istio/api/pull/1698 approved and merged for the experimental, we may need a few API update for alpha)

**Approvals**

- [ ] The appropriate work group(s) have reviewed and approved promotion of the feature. (WIP)
- [ ] The TOC has reviewed and approved promotion of the feature as part of the roadmap for a release. (WIP)

**Comment by brian-avery** [comment]
I've added the checklist for this (https://github.com/brian-avery/enhancements/blob/migrateFeaturesToFiles/features/better_external_authorization.md) to #26
