### ISSUE TITLE
[Stable] Auto mutual TLS.

### ISSUE THREAD

**Issue by incfly** [istio/enhancements#27]
# Stable Feature Requirements

This page lists the requirements for promoting a feature to stable. Promotion to stable must meet all requirements of promotion to beta. Please check off and document the steps as they are completed.

**Feature Name:** 

**Alpha Checklist:**

**Beta Checklist:**

**Relevant Documentation:**

--- 

### Requirements: 

**Performance**

- [X] Latency, throughput, and scalability are quantified and documented on
	istio.io.  
https://istio.io/latest/blog/2020/large-scale-security-policy-performance-tests/#data

**Bugs**

- [X ] Feature has no known major issues. 

**Approvals**

TODO: fill these.

- [ ] The appropriate work group(s) have reviewed and approved promotion of the feature.
- [ ] The supportability review panel has reviewed promotion of the feature.  
- [ ] The TOC has reviewed and approved promotion of the feature as part of the
	roadmap for a release.

---

# Beta Checklist

# Beta Feature Requirements

This page lists the requirements for promoting a feature to beta. Promotion to beta must meet all requirements for promotion to alpha. Please check off and document the steps as they are completed.

--- 

### Requirements: 

**Design**

- [X] Design doc describing the intention of the feature, how it will be
	implemented, and any thoughts on how to test the feature has been approved by
	relevant work group leads
- [X] Feature coverage and test plans written and approved. Same above.

**Docs** 

- [X] Documentation on istio.io includes performance expectations; may have caveats. 
      __Same as above, mTLS vs Plaintext performance comparison__
- [X] Documentation on istio.io includes samples/tutorials.
      https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#auto-mutual-tls 
- [x] Documentation on istio.io includes appropriate glossary entries. *TODO*
- [X] All new documentation containing user actions includes istio.io tests. *Not Applied*.
- [X] Release notes have been added. *On By Default Since 1.5, Not Applied*
- [X] Upgrade notes have been added.  *Not Applied*.

**Tests**

TODO: fill these details

- [ ] Integration tests cover feature edge cases.
- [ ] End-to-end tests cover samples/tutorials
- [ ] Fixed issues have tests to prevent regressions
- [ ] Stability/stress test suite includes coverage for the feature.

**Performance**

- [X] Feature coverage and test plans written and approved, [Test Plan Section](https://docs.google.com/document/d/1yEMDRO2FZCyZnDK1AzNmjQtbtQqE7wN8YoM65FAH7uA/edit#heading=h.7df973t639nj)
- [ ] Tests exist with the feature enabled that can be integrated with our automated performance testing.

**API**

- [X] TOC has reviewed the API and determined it to be complete. **Not Applied** No API change.
 
**Tooling**

- [ ] Any necessary tooling to use/debug the feature has been implemented and is complete.

**Comment by howardjohn** [comment]
> Feature has no known major issues.

One concern I have is that workload level PeerAuthentication does not work. Not sure if we consider that a blocker or not?

**Comment by brian-avery** [comment]
Following up from the conversation in the workgroup leads call yesterday, I have created https://github.com/brian-avery/enhancements/blob/migrateFeaturesToFiles/features/auto_mtls.md in #26 to track this.

**Comment by incfly** [comment]
>  workload level PeerAuthentication does not work. Not sure if we consider that a blocker or not?
That's well known since we introduced workload level peer authn. 
https://github.com/istio/istio/pull/21124#issuecomment-588063633.

I think it causes some UX issue and limitations, but for a stability point of view, it has been like this since 1.5  as [documented](https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#enable-mutual-tls-per-namespace-or-workload). Don't feel it's a strong blocker for marking "stable" (from the checklist in the template).

---
@brian-avery  does this mean instead of filing this bug, I should send PRwith status updates on specific feature page once your PR is merged?

**Comment by brian-avery** [comment]
+1. We will track progress using PRs after.

**Comment by incfly** [comment]
Close in favor of https://github.com/istio/enhancements/pull/35
