### ISSUE TITLE
[Alpha] Virtual Service Delegation

### ISSUE THREAD

**Issue by ericvn** [istio/enhancements#5]
# Alpha Feature Requirements

This page lists the requirements for promoting a feature to alpha. Please check off and document the steps as they are completed.

**Feature Name:**  Virtual Service Delegation

**RFC:** see Design Doc

**Design doc:** https://docs.google.com/document/d/1TzXjvbEqeRKHQ7FonAY_yS1zHa8rVH2DIq4EM5BuDQ4/edit#

**Relevant Documentation:** https://istio.io/latest/docs/reference/config/networking/virtual-service/#Delegate

--- 

### Requirements: 

**Design**

- [ ] RFC has been approved describing the intention of the feature as well as the user stories behind the feature. 

**Config**

- [x] Explicit user action is required to enable this feature (e.g. a config field, config resource, or installation action). 

> Link to instructions for enabling
https://istio.io/latest/docs/reference/config/networking/virtual-service/#Delegate

**Docs**

- [x] Reference docs are published to preliminary.istio.io or the Istio wiki.
- [ ] Basic feature docs are published on preliminary.istio.io describing what the feature does, how to use it, and any caveats. 
- [ ] Release notes entries added as appropriate
- [ ] Upgrade notes entries added as appropriate

**Tests**

- [ ] Automated integration tests cover core use cases with the feature enabled. 
- [x] When disabled, the feature does not affect system stability or performance. 

**API**

- [x] Initial API review.  [istio/api#1209](https://github.com/istio/api/pull/1209)

**Approvals**

- [ ] The appropriate work group(s) have reviewed and approved promotion of the feature.
- [ ] The TOC has reviewed and approved promotion of the feature as part of the
	roadmap for a release.

**Comment by linsun** [comment]
subscribe

**Comment by linsun** [comment]
cc @hzxuzhonghu

**Comment by ericvn** [comment]
Just a few links as I was looking into this:

[Change notes for 1.6 where added](https://istio.io/latest/news/releases/1.6.x/announcing-1.6/change-notes/)
[Reference doc from istio.io](https://istio.io/latest/docs/reference/config/networking/virtual-service/#Delegate)
[Initial design doc](https://docs.google.com/document/d/17K0Tbp2Hv1RAkpFxVTIYPLQRuceyUnABtt0amd9ZVow/edit#)
[Second doc with different API (what was implemented)](https://docs.google.com/document/d/1TzXjvbEqeRKHQ7FonAY_yS1zHa8rVH2DIq4EM5BuDQ4/edit#heading=h.xw1gqgyqs5b)
[API PR](https://github.com/istio/api/pull/1209)
[Implementation](https://github.com/istio/istio/pull/22118)
[Open Issue #1](https://github.com/istio/istio/issues/26599)
[Open Issue #2](https://github.com/istio/istio/issues/25204)

[Initial feature request](https://github.com/istio/istio/issues/6070)
[Another feature request](https://github.com/istio/istio/issues/7793)

**Comment by brian-avery** [comment]
Migrated to https://github.com/brian-avery/enhancements/blob/migrateFeaturesToFiles/features/virtual_service_delegation.md as part of #26
