### ISSUE TITLE
[Beta] Canary (Revision Based Install)

### ISSUE THREAD

**Issue by brian-avery** [istio/enhancements#6]
# Beta Feature Requirements

This page lists the requirements for promoting a feature to beta. Promotion to beta must meet all requirements for promotion to alpha. Please check off and document the steps as they are completed.

**Feature Name:** Revision Based Install

**Design Doc:** https://docs.google.com/document/d/1d1z5PC8wvh9QiR3NesAaPm6w2HnE4-KIfjB7GB-_Wf8/edit#heading=h.3z271ayjy5lz

**Alpha Checklist:**

**Primary lead(s):** Brian Avery, Martin Ostrowski

**Relevant Documentation:**
https://istio.io/latest/docs/setup/upgrade/#canary-upgrades

--- 

### Requirements: 

**Design**

- [x] Design doc describing the intention of the feature, how it will be
	implemented, and any thoughts on how to test the feature has been approved by
	relevant work group leads
- [ ] Feature coverage and test plans written and approved.

**Docs** 

- [x] Documentation on istio.io includes performance expectations; may have caveats. 
- [x] Documentation on istio.io includes samples/tutorials. 
- [x] Documentation on istio.io includes appropriate glossary entries. 
- [ ] All new documentation containing user actions includes istio.io tests. **Not yet tested**
- [x] Release notes have been added. 
- [x] Upgrade notes have been added. 

**Tests**

- [ ] Integration tests cover feature edge cases
- [x] End-to-end tests cover samples/tutorials
- [ ] Fixed issues have tests to prevent regressions
- [ ] Stability/stress test suite includes coverage for the feature.

**Performance**

- [ ] Feature coverage and test plans written and approved 
- [ ] Tests exist with the feature enabled that can be integrated with our automated performance testing.

**API**

- [x] TOC has reviewed the API and determined it to be complete. 

**Tooling**

- [x] Any necessary tooling to use/debug the feature has been implemented and is complete. 

**Bugs**

- [ ] Feature has no known major issues.

**Approvals**

- [x] The appropriate work group(s) have reviewed and approved promotion of the feature.
- [ ] The supportability review panel has reviewed promotion of the feature.  
- [x] The TOC has reviewed and approved promotion of the feature as part of the
	road map for a release.

**Comment by ostromart** [comment]
I'm still unable to edit the description, so I'll just comment on the items here:

Design doc Y
Feature coverage and test plans written and approved N https://github.com/istio/istio/issues/27968
 Documentation on istio.io includes performance expectations. N/A
 Documentation on istio.io includes samples/tutorials. Y
 Documentation on istio.io includes appropriate glossary entries. N/A - unclear what this means
 All new documentation containing user actions includes istio.io tests. - unclear what this means
 Release notes have been added. Y
 Upgrade notes have been added. Y
 Integration tests cover feature edge cases Partial
 End-to-end tests cover samples/tutorials Y
 Fixed issues have tests to prevent regressions Unclear
 Stability/stress test suite includes coverage for the feature. N/A
 Feature coverage and test plans written and approved N 
 Tests exist with the feature enabled that can be integrated with our automated performance testing. https://github.com/istio/istio/issues/27968
 TOC has reviewed the API and determined it to be complete. Y
 Any necessary tooling to use/debug the feature has been implemented and is complete. Y
 Feature has no known major issues. Y
 The appropriate work group(s) have reviewed and approved promotion of the feature. Y
 The supportability review panel has reviewed promotion of the feature. Y
 The TOC has reviewed and approved promotion of the feature as part of the road map for a release. Y

**Comment by brian-avery** [comment]
Thanks. 

Documentation on istio.io includes appropriate glossary entries -- this is just encouraging docs to be written. I.e. if new terms are added as part of the reference, tasks, etc then they should be defined in the glossary. I looked and didn't see anything in the documentation that looked like it hadn't been defined yet. 

All new documentation containing user actions includes istio.io tests.  -- Any documentation for a feature that includes user steps should be documented. For example, tasks. In this case, we have documentation at https://istio.io/latest/docs/setup/upgrade/ that doesn't yet have any tests written.

**Comment by ostromart** [comment]
We do have tests, but not in the framework: https://github.com/istio/tools/pull/1222
Upgrade is sort of special in that it doesn't fit within the framework we have, which assumes that the cluster itself already exists.
